FROM node:24 as build
WORKDIR /frontend
COPY package*.json ./
RUN npm ci
COPY tsconfig*.json ./
COPY index.html ./
COPY . .
RUN npm run build
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# hello world